In [ ]:
%pip install numpy

     ---------------------------------------- 0.0/60.9 kB ? eta -:--:--
     ---------------------------------------- 60.9/60.9 kB 3.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.4/12.7 MB 8.7 MB/s eta 0:00:02
   -- ------------------------------------- 0.9/12.7 MB 10.9 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/12.7 MB 10.6 MB/s eta 0:00:02
   ----- ---------------------------------- 1.8/12.7 MB 10.5 MB/s eta 0:00:02
   ------- -------------------------------- 2.3/12.7 MB 10.3 MB/s eta 0:00:02
   -------- ------------------------------- 2.8/12.7 MB 10.4 MB/s eta 0:00:01
   ---------- ----------------------------- 3.3/12.7 MB 10.7 MB/s eta 0:00:01
   ------------ --------------------------- 3.9/12.7 MB 10.7 MB/s eta 0:00:01
   ------------- -------------------------- 4.3/12.7 MB 11.0 MB/s eta 0:00:01
   --------------- ------------------------ 4.9/12.7 MB 11.1 MB/s eta 0:00:01


[notice] A new release of pip is available: 23.3.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

arr1 = np.array([[1,2,3,4,5]])
print(arr1)
print(type(arr1))
print(arr1.shape)




[[1 2 3 4 5]]
<class 'numpy.ndarray'>
(1, 5)


In [ ]:
import numpy as np 

num = np.array([[1,2],[2,3],[3,4]])

print("shape of the array is ",num.shape)
print("max: ",num.partition(3))

print(num)

shape of the array is  (3, 2)


ValueError: kth(=3) out of bounds (2)

In [16]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# identity matrix and array 

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition",arr1+arr2)

print("Subtraction: ",arr1-arr2)

print("multiplication: ",arr1*arr2)

Addition [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
multiplication:  [ 10  40  90 160 250]


In [ ]:
#universal functions , functions applies to entire array

arr = np.array

In [4]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [15]:
print(arr[0:2,0:3])

[[1 2 3]
 [5 6 7]]


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# newarr = arr.reshape(4, 3)
print(arr)

newarr = arr.reshape(6,2)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
